#!/bin/sh

[ -z "$GRAALVM_HOME" ] && echo "GRAALVM_HOME is currently not set. This script will not work." && exit 1
[ ! -f "$GRAALVM_HOME/bin/native-image" ] && echo "Can't find native-image in $GRAALVM_HOME. Check that the directory is valid." && exit 1
[ -z "$SCALA_HOME" ] && echo "SCALA_HOME is currently not set. This script will not work." && exit 1

if [[ $# -gt 1 ]]; then
  echo 'run scala sc file'
  exit 1
fi

loc="$(dirname "$0")"
SCALA_LIB="$SCALA_HOME/lib"

sourceFileName=$1
sourceJar="$sourceFileName.jar"
outputName="${sourceJar%.*}.run"


if [ -f $outputName ]; then
   if [ "$outputName" -ot "$sourceFileName" ]; then
     rm $outputName
   else
     $outputName
     exit $? 
   fi
fi

$SCALA_HOME/bin/scala -savecompiled "$@" > /dev/null

if [ -d "$SCALA_HOME/libexec" ]; then
  SCALA_LIB="$SCALA_HOME/libexec/lib"
fi

[ ! -d "$SCALA_LIB" ] && echo "Can't find jars in $SCALA_LIB. Check that the Scala instalation is correct." && exit 1
for filename in $SCALA_LIB/*.jar; do
  SCALA_LIB_CLASSPATH=$filename:$SCALA_LIB_CLASSPATH
done

mainClassName="Main"
cpath="$sourceJar:$SCALA_LIB_CLASSPATH:$loc/substitutions_2.12-0.1.0-SNAPSHOT.jar"

$GRAALVM_HOME/bin/native-image -J-Xmx8G -J-Xms6G -cp "$cpath" $mainClassName \
  -H:SubstitutionResources=substitutions.json,substitutions-2.12.json \
  -H:ReflectionConfigurationFiles=$loc/reflection-config.json \
  -H:Name="$outputName"

rm $sourceJar
$outputName
